name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      URI_MONGO_DB: ${{ secrets.MONGO_CONNECTION_STRING }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm test
